"""add uploaded_files and service_logs tables

Revision ID: d42d074d5a42
Revises:
Create Date: 2026-09-21 19:18:05.887222

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d42d074d5a42"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uploaded_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.Uuid(), nullable=False),
        sa.Column(
            "original_filename",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "file_extension",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=False,
        ),
        sa.Column(
            "content_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "gcs_bucket_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "storage_object_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "IN_PROGRESS", "SUCCESS", "ERROR", name="fileprocessingstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "error_code",
            sa.Enum(
                "INVALID_EXTENSION",
                "EMPTY_FILE",
                "INVALID_CSV_FORMAT",
                "SCHEMA_MISMATCH",
                "DATA_CLEANING_FAILED",
                "STORAGE_UPLOAD_FAILED",
                "STORAGE_DOWNLOAD_FAILED",
                "DATABASE_CONNECTION_FAILED",
                "DATABASE_WRITE_FAILED",
                "FILE_RECORD_NOT_FOUND",
                "UNKNOWN_ERROR",
                name="fileprocessingerrorcode",
            ),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            sqlmodel.sql.sqltypes.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_uploaded_files_guid"), "uploaded_files", ["guid"], unique=True
    )
    op.create_index(
        op.f("ix_uploaded_files_id"), "uploaded_files", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_uploaded_files_status"), "uploaded_files", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_uploaded_files_storage_object_name"),
        "uploaded_files",
        ["storage_object_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_uploaded_files_uploaded_at"),
        "uploaded_files",
        ["uploaded_at"],
        unique=False,
    )
    op.create_table(
        "service_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column(
            "service_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "service_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "region", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploaded_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_logs_id"), "service_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_service_logs_recorded_at"),
        "service_logs",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_logs_service_id"), "service_logs", ["service_id"], unique=False
    )
    op.create_index(
        "ix_service_logs_service_id_recorded_at",
        "service_logs",
        ["service_id", "recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_logs_service_name"),
        "service_logs",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_logs_status_code"),
        "service_logs",
        ["status_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_logs_upload_id"), "service_logs", ["upload_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_logs_upload_id"), table_name="service_logs")
    op.drop_index(op.f("ix_service_logs_status_code"), table_name="service_logs")
    op.drop_index(op.f("ix_service_logs_service_name"), table_name="service_logs")
    op.drop_index("ix_service_logs_service_id_recorded_at", table_name="service_logs")
    op.drop_index(op.f("ix_service_logs_service_id"), table_name="service_logs")
    op.drop_index(op.f("ix_service_logs_recorded_at"), table_name="service_logs")
    op.drop_index(op.f("ix_service_logs_id"), table_name="service_logs")
    op.drop_table("service_logs")
    op.drop_index(op.f("ix_uploaded_files_uploaded_at"), table_name="uploaded_files")
    op.drop_index(
        op.f("ix_uploaded_files_storage_object_name"), table_name="uploaded_files"
    )
    op.drop_index(op.f("ix_uploaded_files_status"), table_name="uploaded_files")
    op.drop_index(op.f("ix_uploaded_files_id"), table_name="uploaded_files")
    op.drop_index(op.f("ix_uploaded_files_guid"), table_name="uploaded_files")
    op.drop_table("uploaded_files")
    # ### end Alembic commands ###
